[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1097307751388024864
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Entrando no Modpack"
	#The second line of text under the app name
	state = "Carregando..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um servidor de modpack da %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[init.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% Está no menu principal"
	#The second line of text under the app name
	state = "Observando o menu"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[main_menu.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% Indo jogar no MekaMiners!"
	#The second line of text under the app name
	state = "Se juntando a nossa comunidade"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[server_list.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "Procurando por um Realm?"
	#The second line of text under the app name
	state = "É sério isso?"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "?"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[realms_list.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Entrando no jogo"
	#The second line of text under the app name
	state = "Entrando no mapa"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = []
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[join_game.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Jogando no mundo: %world%"
	#The second line of text under the app name
	state = "Jogando SinglePlayer"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[single_player.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Jogando no MekaMiners Rebirth com %players% players"
	#The second line of text under the app name
	state = "Jogando com amigos"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[multi_player.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Jogando no %realmname%"
	#The second line of text under the app name
	state = "Jogando em um Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[realms.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[generic]
	#The first line of text under the app name
	description = "Jogando MekaMiners Rebirth!"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://i.imgur.com/HkdrBEG.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["logos1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[generic.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = ["overworld"]
		largeImageText = "In the Overworld"
		smallImageKey = ["mclogo"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = ["nether"]
		largeImageText = "In the Nether"
		smallImageKey = ["mclogo"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = ["end"]
		largeImageText = "In the End"
		smallImageKey = ["mclogo"]
		smallImageText = "%mods% mods installed"
		buttons = []


